#!/bin/bash
###########################################################
# macOS Development Environment Setup
#
# Copyright (c) Marcos Gomes-Borges
###########################################################
# This script installs to /usr/local
# To install elsewhere you can clone the project
#   git clone https://github.com/marcosgomesborges/dev-setup
###########################################################
INSTALL_VERSION="0.0.2"
DEVSETUP_URL="https://raw.githubusercontent.com/marcosgomesborges/dev-setup/master/macos/devsetup"
DEVSETUP_PREFIX="/usr/local/bin"

red="\033[91m"
green="\033[92m"
yellow="\033[93m"
blue="\033[94m"
magenta="\033[95m"
nc="\033[39m"

wait_for_user() {
    printf "${yellow}\nPress RETURN to continue or any other key to abort!\n${nc}"

    read -s -n 1 key
    if [[ ${key} != "" ]]; then
        printf "${red}\nInstallation aborted!${nc}"
        exit 1
    fi
}

printf "${magenta}\nCurrent directory: ${nc}"
printf "`pwd`\n"
printf "${magenta}This script installs 'devsetup' to: ${nc}"
printf "${DEVSETUP_PREFIX}\n"

wait_for_user

curl -fsSL "${DEVSETUP_URL}" -o "${DEVSETUP_PREFIX}/devsetup"
chmod +x "${DEVSETUP_PREFIX}/devsetup"

printf "${green}\nUpdate successful\n\n${nc}"
devsetup --help
