#!/bin/bash
###########################################################
# macOS Development Environment Setup
#
# Copyright (c) Marcos Gomes-Borges
###########################################################
# This script installs to /usr/local
# To install elsewhere you can clone the project
#   git clone https://github.com/marcosgomesborges/dev-setup
###########################################################
VERSION='0.0.2'
MACOS_URL='https://raw.githubusercontent.com/marcosgomesborges/dev-setup/master/macos'

usage() {
cat <<EOF
    Usage: macos [OPTIONS]

    Option          Long option         Meaning
    -h              --help              Show this help text and exit
    -v              --version           Show the version number of macos-setup
EOF
}

print_version() {
  echo -e "macos-setup ${VERSION}"
}

usage_fatal() { echo -e "${*}\n"; usage >&2; }


# Update macos-setup script
###########################################################
macos_update() {
    echo -e "Updating macos-setup ${VERSION}"
    curl -fsSL ${MACOS_URL} -o /usr/local/bin/macos && chmod +x /usr/local/bin/macos
}


# Parse options
###########################################################
while [ "$#" -gt 0 ]; do
    case $1 in
        --*'='*)
            shift
            set -- "${1%%=*}" "${1#*=}" "$@"
            continue
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -u|--update)
            macos_update
            exit 0
            ;;
        -v|--version)
            print_version
            exit 0
            ;;
        --|-*|*)
            usage_fatal "unknown option: ${1}"
            exit 1
            ;;
    esac
    shift
done
