#!/bin/bash
###########################################################
# Development Environment Setup
#
# Copyright (c) Marcos Gomes-Borges
###########################################################
VERSION="0.0.1"
DEVSETUP_URL="https://raw.githubusercontent.com/marcosgomesborges/dev-setup/master/macos/devsetup"
DEVSETUP_PREFIX=`pwd`

# devsetup usage
###########################################################
usage() {
cat <<EOF
    Usage: devsetup [OPTIONS]

    Option          Long option         Meaning
    -h              --help              Show this help text and exit
    -v              --version           Show the version number of devsetup script
EOF
}

# devsetup install usage
###########################################################
usage_install() {
cat <<EOF
    Usage: devsetup install [SCRIPT]

    Script          Description
    homebrew        Install homebrew package manager for macOS
EOF
}

# Print formated message
# print COLOR FRAME MSG
###########################################################
print() {
    COLOR=$1
    FRAME=$2
    MSG=$3

    case "${COLOR}" in
        *"red"*)
            COLOR="\033[91m";;
        *"green"*)
            COLOR="\033[92m";;
        *"yellow"*)
            COLOR="\033[93m";;
        *"blue"*)
            COLOR="\033[94m";;
        *"magenta"*)
            COLOR="\033[95m";;
        *)
            COLOR="\033[39m";;
    esac

    case "${FRAME}" in
        "frame")
            echo -e "${COLOR}`printf "=%0.s" {0..79}`"
            echo -e "${COLOR}${MSG}"
            echo -e "${COLOR}`printf "=%0.s" {0..79}`"
            ;;
        *)
            echo -e "${COLOR}${MSG}"
            ;;
    esac

    echo -e "\033[39m" # default color
}

# Print the version number of devsetup script
###########################################################
print_version() {
  echo -e "devsetup ${VERSION}"
}

# Usage error
###########################################################
usage_fatal() { print red "${*}"; usage >&2; }
usage_install_fatal() { print red "${*}"; usage_install >&2; }

# devsetup install homebrew
###########################################################
devsetup_install_homebrew() {
    print yellow frame "Starting Homebrew installation"

    # Installing GCC
    print yellow "Installing the GNU Compiler Collection (GCC)"

    # Install the Command Line Tools package
    xcode-select --install

    # Install the additional SDK headers
    sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

    # Installing Homebrew
    print yellow "Installing Homebrew"

    if hash brew 2>/dev/null; then
        print green "Brew is already installed - updating ..."
        brew update
        brew upgrade
    else
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    print green frame "Homebrew installation successful"
}

# devsetup install
###########################################################
devsetup_install() {
    case ${@} in
        "homebrew")
            devsetup_install_homebrew
            exit 0
            ;;
        ""|*)
            usage_install_fatal "invalid installation command"
            exit 1
            ;;
    esac
}

# devsetup update devsetup
###########################################################
devsetup_update_devsetup() {
    print yellow "This update installs to ${DEVSETUP_PREFIX}/devsetup"
    print default "Press RETURN to continue or any other key to abort"

    read -s -n 1 key
    if [[ $key != "" ]]; then
        print red "\nUpdate aborted!"
        exit 1
    fi

    curl -fsSL "${DEVSETUP_URL}" -o "${DEVSETUP_PREFIX}/devsetup" && \
    chmod +x "${DEVSETUP_PREFIX}/devsetup"

    print green "\nUpdate successful"
}

# devsetup update
###########################################################
devsetup_update() {
    case ${@} in
        "devsetup")
            devsetup_update_devsetup
            exit 0
            ;;
        ""|*)
            usage_install_fatal "invalid update command"
            exit 1
            ;;
    esac
}

# Parse options
###########################################################
while [ "${#}" -gt 0 ]; do
    case ${1} in
        --*'='*)
            shift
            set -- "${1%%=*}" "${1#*=}" "$@"
            continue
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -v|--version)
            print_version
            exit 0
            ;;
        -i|--install)
            shift
            devsetup_install ${1}
            exit 0
            ;;
        -u|--update)
            devsetup_update ${1}
            exit 0
            ;;
        --|-*|*)
            usage_fatal "unknown option: ${1}"
            exit 1
            ;;
    esac
    shift
done
