#!/bin/bash
###########################################################
# Development Environment Setup
#
# Copyright (c) Marcos Gomes-Borges
###########################################################
VERSION="0.0.2"
DEVSETUP_URL="https://raw.githubusercontent.com/marcosgomesborges/dev-setup/master/macos/devsetup"
DEVSETUP_PREFIX=$(dirname $0)

red="\033[91m"
green="\033[92m"
yellow="\033[93m"
blue="\033[94m"
magenta="\033[95m"
resetcolor="\033[39m"

# devsetup usage
###########################################################
usage() {
cat <<EOF
    Usage: devsetup [OPTIONS]

    Option          Long option         Meaning
    -h              --help              Show this help text and exit
    -v              --version           Show the version number of devsetup script
    -i              --install           Install a package
    -u              --update            Update a package
EOF
}

# devsetup install usage
###########################################################
usage_install() {
cat <<EOF
    Usage: devsetup install [SCRIPT]

    Script          Description
    homebrew        Install homebrew package manager for macOS
    git             Install and set-up git
    bash            Install the latest version of Bash
EOF
}

# devsetup update usage
###########################################################
usage_update() {
cat <<EOF
    Usage: devsetup update [SCRIPT]

    Script          Description
    devsetup        Update devsetup
EOF
}

# Print formated message: print <color> <frame> "message"
###########################################################
print() {
    case ${#} in
        "1") COLOR=resetcolor; FRAME=false; MSG=${1} ;;
        "2") COLOR=${1}; FRAME=false; MSG=${2} ;;
        "3") COLOR=${1}; FRAME=${2}; MSG=${3} ;;
    esac

    if [[ ${FRAME} = "frame" ]]; then
        printf "${!COLOR}`printf "=%0.s" {0..79}`\n"
        printf "${!COLOR}${MSG}"
        printf "${!COLOR}`printf "=%0.s" {0..79}`\n"
    else
        printf "${!COLOR}${MSG}"
    fi

    printf ${resetcolor}
}

# Check Press RETURN to continue
###########################################################
wait_for_user() {
    print yellow "\nPress RETURN to continue or any other key to abort!\n"

    read -s -n 1 key

    if [[ ${key} != "" ]]; then
        exit 0
    fi
}

# Print the version number of devsetup script
###########################################################
print_version() {
  print "devsetup ${VERSION}\n"
}

# Usage error
###########################################################
usage_fatal() {
    print red "devsetup: illegal option ${@}\n"
    usage >&2
}

usage_install_fatal() {
    print red "devsetup install: illegal option ${@}\n"
    usage_install >&2
}

usage_update_fatal() {
    print red "devsetup update: illegal option ${@}\n"
    usage_update >&2
}

# Check if Homebrew is installed and update it
###########################################################
homebrew_update() {
    if hash brew 2>/dev/null; then
        print green "Homebrew is already installed - updating ...\n"
        brew update
    else
        print red "Homebrew is not installed! Install it with: "
        print "desetup --install homebrew\n"
        exit 1
    fi
}

# devsetup install homebrew
###########################################################
devsetup_install_homebrew() {
    print magenta "Installing the GNU Compiler Collection (GCC)\n"
    xcode-select --install

    print magenta "Installing Command Line Tools additional headers\n"
    sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

    if hash brew 2>/dev/null; then
        print green "Homebrew is already installed - updating ...\n"
        brew update
        brew upgrade
    else
        print magenta "Installing Homebrew\n"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    print green frame "Homebrew installation successful\n"
}

# devsetup install git
###########################################################
devsetup_git_config() {
    print magenta frame "GIT configuration\n"

    print yellow "git config --global user.name \"Your name\": "
    read GIT_USER_NAME

    print yellow "git config --global user.email \"your@email.com\": "
    read GIT_USER_EMAIL

    # Confirm user input
    print magenta "\nUser Name: "
    print "${GIT_USER_NAME}\n"
    print magenta "E-mail: "
    print "${GIT_USER_EMAIL}\n"

    wait_for_user

    # Set git user name and email
    git config --global user.name "${GIT_USER_NAME}"
    git config --global user.email "${GIT_USER_EMAIL}"

    # Set git terminal colors
    git config --global color.ui true
    git config --global color.status.changed "blue normal"
    git config --global color.status.untracked "red normal"
    git config --global color.status.added "magenta normal"
    git config --global color.status.updated "green normal"
    git config --global color.status.branch "yellow normal bold"
    git config --global color.status.header "white normal bold"
}

devsetup_install_git() {
    homebrew_update
    brew install git
    devsetup_git_config

    print green frame "Git installation successful\n"
}

# devsetup install bash
###########################################################
devsetup_install_bash() {
    set -e

    homebrew_update
    brew install bash

    if [[ `cat /etc/shells | grep '/usr/local/bin/bash'` = "" ]]; then
        print magenta "Adding the new shell to the list of allowed shells\n"
        sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'

        print magenta "Changing to the new shell\n"
        chsh -s /usr/local/bin/bash
    fi

    print green frame "Bash installation successful\n"
}

# devsetup install
###########################################################
devsetup_install() {
    case ${@} in
        "homebrew")
            devsetup_install_homebrew
            exit 0
            ;;
        "git")
            devsetup_install_git
            exit 0
            ;;
        "bash")
            devsetup_install_bash
            exit 0
            ;;
        ""|*)
            usage_install_fatal ${@}
            exit 1
            ;;
    esac
}

# devsetup update devsetup
###########################################################
devsetup_update_devsetup() {
    print magenta "\nCurrent directory: "
    print "`pwd`\n"
    print magenta "This update installs 'devsetup' to: "
    print "${DEVSETUP_PREFIX}\n"

    wait_for_user

    curl -fsSL "${DEVSETUP_URL}" -o "${DEVSETUP_PREFIX}/devsetup"
    chmod +x "${DEVSETUP_PREFIX}/devsetup"

    print green "\nUpdate successful\n"
}

# devsetup update
###########################################################
devsetup_update() {
    case ${@} in
        "devsetup")
            devsetup_update_devsetup
            exit 0
            ;;
        ""|*)
            usage_update_fatal ${@}
            exit 1
            ;;
    esac
}

# Parse options
###########################################################
while [ "${#}" -gt 0 ]; do
    case ${1} in
        --*'='*)
            shift
            set -- "${1%%=*}" "${1#*=}" "$@"
            continue
            ;;
        -h|--help)
            print_version
            usage
            exit 0
            ;;
        -v|--version)
            print_version
            exit 0
            ;;
        -i|--install)
            shift
            devsetup_install ${1}
            exit 0
            ;;
        -u|--update)
            shift
            devsetup_update ${1}
            exit 0
            ;;
        --|-*|*)
            usage_fatal ${1}
            exit 1
            ;;
    esac
    shift
done
