#!/bin/bash
###########################################################
# Development Environment Setup
#
# Copyright (c) Marcos Gomes-Borges
###########################################################
VERSION="0.0.8"
DEVSETUP_URL="https://raw.githubusercontent.com/marcosgomesborges/dev-setup/master/macos/devsetup"
DEVSETUP_PREFIX="/usr/local"

red="\033[91m"
green="\033[92m"
yellow="\033[93m"
blue="\033[94m"
magenta="\033[95m"
nc="\033[39m"

usage() {
cat <<EOF
    Usage: devsetup [OPTIONS]

    Option          Long option         Meaning
    -h              --help              Show this help text and exit
    -v              --version           Show the version number of devsetup script
    -i              --install           Install a package
    -u              --update            Update a package
EOF
}

usage_install() {
cat <<EOF
    Usage: devsetup install [SCRIPT]

    Script              Description
    homebrew            Install homebrew package manager for macOS
    git                 Install and setup git
    bash                Install the latest version of Bash
    bash-tab-completion Install bash tab completion 2
    pyenv               Install multiple Python versions using 'pyenv'
    pylibs              Install Python Libraries: TensorFlow, Keras, scientific libraires
    jupyterlab          Install Jupyterlab with extensions: toc, git, matplotlib
    ffmpeg              Install FFmpeg with all modules
    opencv              Install OpenCV 4.1.0
    all                 Install all the packages
EOF
}

usage_update() {
cat <<EOF
    Usage: devsetup update [SCRIPT]

    Script          Description
    devsetup        Update devsetup
    git             Setup git with username, email, and terminal colors
    bash-profile    Setup bash_profile
    inputrc         Improve command line history search
    vscode          Setup Visual Studio Code and install extensions
EOF
}

read -r -d '' BASH_PROFILE <<"EOF"
# !/bin/bash
###########################################################
# Bash Profile
#
# Copyright (c) Marcos Gomes-Borges
###########################################################

# LS Colors
# CLICOLOR use ANSI color sequences to distinguish file types
export CLICOLOR=true
export LSCOLORS=gxegbxdxcxahadabafacge
alias ls='ls -GFh'

# COLORS \e[<prefix>;<color>m;<decoration> http://jonasjacek.github.io/colors
TEAL="\[\e[38;5;6m\]\]"
YELLOW="\[\e[38;5;11m\]"
MAGENTA="\[\e[38;5;13m\]"
WHITE="\[\e[38;5;15m\]"
GREEN="\[\e[38;5;40m\]"
NONE="\[\e[0m\]"

# Prevent Mac OS ._ in in tar.gz files
export COPYFILE_DISABLE=true

# Homebrew
export PATH="/usr/local/bin:${PATH}"

# Homebrew completion
if [ -f $(brew --prefix)/etc/bash_completion.d/brew ]; then
    . $(brew --prefix)/etc/bash_completion.d/brew
fi

# Bash completion@2
if [ -f /usr/local/share/bash-completion/bash_completion ]; then
  . /usr/local/share/bash-completion/bash_completion
fi

# Bash-Git-prompt
if [ -f $(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh ]; then
    __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share

    GIT_PS1_SHOWCOLORHINTS=true
    GIT_PS1_SHOWDIRTYSTATE=true
    GIT_PS1_SHOWUNTRACKEDFILES=true
    GIT_PS1_DESCRIBE_STYLE='default'

    source $(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh
fi

# Python virtual environment
# Allow pip only for active virtual environment
# Use `gpip` or `gpip3` for global environment
export PIP_REQUIRE_VIRTUALENV=true
gpip(){
    PIP_REQUIRE_VIRTUALENV="" pip "${@}"
}
gpip3(){
    PIP_REQUIRE_VIRTUALENV="" pip3 "${@}"
}

# Pyenv Python version management
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
    pyenv virtualenvwrapper
fi

# PRIMARY PROMPT
PROMPT_COMMAND='__git_ps1\
                "\n${MAGENTA}[\d \t] ${YELLOW}`(python --version 2>&1)`${NONE}\
                \n${GREEN}\u@\h:${TEAL}\w${NONE}"\
                "\n${VIRTUAL_ENV:+(`basename ${VIRTUAL_ENV}`)}\\$ "\
                " (%s)"'
EOF

read -r -d '' INPUTRC <<"EOF"
"\e[A":history-search-backward
"\e[B":history-search-forward

set colored-stats on
set mark-symlinked-directories on
set show-all-if-ambiguous on
set show-all-if-unmodified on
set visible-stats on
set completion-ignore-case on
TAB: menu-complete
EOF

# Print a formated message: print <color> <frame> "message"
print() {
    case ${#} in
        "1") COLOR=nc; FRAME=false; MSG=${1} ;;
        "2") COLOR=${1}; FRAME=false; MSG=${2} ;;
        "3") COLOR=${1}; FRAME=${2}; MSG=${3} ;;
    esac

    if [[ ${FRAME} = "frame" ]]; then
        printf "${!COLOR}`printf "=%0.s" {0..79}`\n"
        printf "${!COLOR}${MSG}"
        printf "${!COLOR}`printf "=%0.s" {0..79}`\n"
    else
        printf "${!COLOR}${MSG}"
    fi

    printf ${nc}
}

wait_for_user() {
    print yellow "\nPress RETURN to continue or any other key to abort!\n"

    read -s -n 1 key
    if [[ ${key} != "" ]]; then
        exit 0
    fi
}

wait_for_sudo() {
    trap "exit 1" SIGINT # Process Interruption Ctrl-C

    # Check if sudo password has been entered
    # If not, request sudo password
    if sudo -vn 2>/dev/null; then
        print blue "\n[sudo] this script is using sudo privileges!\n\n"
    else
        print yellow "\n[sudo] Enter password for ${USER}\n"
        sudo -v
    fi

    # Abort if no sudo privileges
    if ! sudo -vn 2>/dev/null; then
        print red "Aborted: "
        print "this script needs sudo privileges!\n"
        exit 1
    fi
}

print_version() {
  print "devsetup ${VERSION}\n"
}

usage_fatal() {
    print red "devsetup: illegal option ${@}\n"
    usage >&2
}

usage_install_fatal() {
    print red "devsetup install: illegal option ${@}\n"
    usage_install >&2
}

usage_update_fatal() {
    print red "devsetup update: illegal option ${@}\n"
    usage_update >&2
}

# Check if Homebrew is installed and update it
homebrew_update() {
    if hash brew 2>/dev/null; then
        print green "Homebrew is already installed - updating ...\n"
        brew update
    else
        print red "Homebrew is not installed! Install it with: "
        print "devsetup --install homebrew\n"
        exit 1
    fi
}

devsetup_install_homebrew() {
    wait_for_sudo

    print magenta "Installing the GNU Compiler Collection (GCC)\n"
    xcode-select --install

    print magenta "Installing Command Line Tools additional headers\n"
    sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

    if hash brew 2>/dev/null; then
        print green "Homebrew is already installed - updating ...\n"
        brew update
        brew upgrade
    else
        print magenta "Installing Homebrew\n"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    print green frame "Homebrew installation successful\n"
}

devsetup_git_config() {
    print magenta frame "GIT configuration\n"

    print yellow "git config --global user.name \"Your name\": "
    read GIT_USER_NAME

    print yellow "git config --global user.email \"your@email.com\": "
    read GIT_USER_EMAIL

    # Confirm user input
    print magenta "\nUser Name: "
    print "${GIT_USER_NAME}\n"
    print magenta "E-mail: "
    print "${GIT_USER_EMAIL}\n"

    wait_for_user

    # Set git user name and email
    git config --global user.name "${GIT_USER_NAME}"
    git config --global user.email "${GIT_USER_EMAIL}"

    # Set git terminal colors
    git config --global color.ui true
    git config --global color.status.changed "blue normal"
    git config --global color.status.untracked "red normal"
    git config --global color.status.added "magenta normal"
    git config --global color.status.updated "green normal"
    git config --global color.status.branch "yellow normal bold"
    git config --global color.status.header "white normal bold"
}

devsetup_install_git() {
    homebrew_update
    brew install git
    devsetup_git_config

    print green frame "Git installation successful\n"
}

devsetup_install_bash() {
    wait_for_sudo
    homebrew_update
    brew install bash

    if [[ `cat /etc/shells | grep '/usr/local/bin/bash'` = "" ]]; then
        print magenta "Adding the new shell to the list of allowed shells\n"
        sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'

        print magenta "Changing to the new shell\n"
        chsh -s /usr/local/bin/bash
    fi

    print green frame "Bash installation successful\n"
}

devsetup_install_bash_tab_completion() {
    wait_for_sudo
    homebrew_update

    print magenta "Install bash TAB completion 2\n"
    brew install bash-completion@2

    print magenta "Install Informative git-prompt\n"
    brew install bash-git-prompt

    print magenta "Install Docker-machine bash TAB completion\n"
    sudo curl -L https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash -o /usr/local/etc/bash_completion.d/docker-machine

    print magenta "Install Docker-compose bash TAB completion\n"
    sudo curl -L https://raw.githubusercontent.com/docker/compose/1.24.0/contrib/completion/bash/docker-compose -o /usr/local/etc/bash_completion.d/docker-compose

    print green frame "Bash TAB Completion installation successful\n"
}

devsetup_install_pyenv() {
    homebrew_update

    print magenta "Installing pyenv\n"
    brew install pyenv

    print magenta "Installing pyenv-virtualenvwrapper\n"
    brew install pyenv-virtualenvwrapper

    print magenta "Installing Python 2.7.15, 3.6.5, 3.7.3\n"
    eval "$(pyenv init -)"
    PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 2.7.15
    PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.5
    PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.7.3

    print magenta "Setting up Python 3.6.5 as default\n"
    pyenv global 3.6.5

    print magenta "Setting up virtualenvwrapper\n"
    pyenv virtualenvwrapper

    print green frame "pyenv installation successful\n"
}

workon_virtual_environment_py365() {
    # Check Pyenv - Python installation management
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
        pyenv shell 3.6.5
        pyenv virtualenvwrapper
        mkvirtualenv py365 # Workon/Create virtual environment 'py365'
    else
        print red "Pyenv is not installed! Install it with: "
        print "devsetup --install pyenv\n"
        exit 1
    fi
}

devsetup_install_python_libraries() {
    print magenta frame "Install Python libraries dependencies\n"
    homebrew_update

    # Install Graphviz - Keras dependency
    brew install Graphviz

    print magenta frame "Create a python virtual environment 'py365'\n"
    workon_virtual_environment_py365

    print magenta frame "Installing Python libraries\n"
    workon py365
    pip install --no-cache-dir --upgrade pip

    # TensorFlow
    pip install --no-cache-dir --upgrade tensorflow

    # Keras
    pip install --no-cache-dir --upgrade \
        h5py \
        pydot \
        keras

    # Scientific libraires
    pip install --no-cache-dir  --upgrade \
        pandas \
        scipy \
        pillow \
        scikit-learn \
        scikit-image \
        sk-video

    # Basic libraries
    pip install --no-cache-dir --upgrade \
        progressbar2 \
        requests \
        Cython \
        pylint \
        autopep8 \
        pytest \
        pydocstyle

    # Matplotlib
    pip install --no-cache-dir --upgrade \
        ipympl \
        matplotlib

    # Fix Matplotlib backend
    mkdir -p ~/.config/matplotlib
    echo "backend : TkAgg" > ~/.config/matplotlib/matplotlibrc

    print green frame "Python libraries installation successful\n"
}

devsetup_install_jupyterlab() {
    print magenta frame "Install Jupyterlab\n"

    workon_virtual_environment_py365
    workon py365
    pip install --no-cache-dir --upgrade \
        pip \
        jupyterlab \
        jupyterlab-git

    print magenta frame "Installing Jupyterlab extensions (Require Node.js)\n"
    homebrew_update
    brew install node # Jupyterlab extensions dependency
    workon py365

    jupyter labextension install @jupyterlab/toc
    jupyter labextension install @jupyterlab/git
    jupyter serverextension enable --py jupyterlab_git

    jupyter labextension install @jupyter-widgets/jupyterlab-manager
    jupyter labextension install jupyter-matplotlib

    # Cleanup
    print magenta frame "Cleanup - removing temporary files\n"
    npm cache clean --force

    print green frame "Jupyterlab installation successful\n"
}

devsetup_install_ffmpeg() {
    print magenta frame "Install FFmpeg\n"
    homebrew_update
    brew install ffmpeg $(brew options ffmpeg | grep -E '^--with-' - | tr '\n' ' ')
    print green frame "FFmpeg installation successful\n"
}

devsetup_install_opencv() {
    print magenta frame "Download, configure and install Opencv\n"

    OPENCV_VERSION="4.1.0"
    OPENCV_URL="https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.tar.gz"
    OPENCV_CONTRIB_URL="https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.tar.gz"

    print magenta "Installing Opencv dependencies\n"
    homebrew_update

    brew install cmake pkg-config jpeg webp gphoto2 libpng libtiff openexr eigen tbb

    workon_virtual_environment_py365
    workon py365

    pip install --no-cache-dir --upgrade pip numpy
    devsetup_install_ffmpeg

    print magenta "DOWNLOADING OpenCV files\n"
    mkdir -p "${DEVSETUP_PREFIX}/DevSetup/OpenCV"
    cd "${DEVSETUP_PREFIX}/DevSetup/OpenCV"

    if [[ -e "opencv.tar.gz" && -e "opencv_contrib.tar.gz" ]]; then
        print magenta "Using local files: \n"
        print "${DEVSETUP_PREFIX}/DevSetup/OpenCV/opencv.tar.gz\n"
        print "${DEVSETUP_PREFIX}/DevSetup/OpenCV/opencv_contrib.tar.gz\n"
    else
        curl -L ${OPENCV_URL} -o "opencv.tar.gz"
        curl -L ${OPENCV_CONTRIB_URL} -o "opencv_contrib.tar.gz"
    fi

    tar -xzf opencv.tar.gz
    tar -xzf opencv_contrib.tar.gz

    mkdir -p opencv-${OPENCV_VERSION}/build
    cd opencv-${OPENCV_VERSION}/build

    print magenta "CONFIGURING OpenCV installation\n"
    set -e # Exit immediately if the pipeline fail

    # Automatically ENABLE/DISABLE Qt
    if ls $HOME/Qt*/*/clang_64/bin/qmake 1>/dev/null 2>&1; then
        QT_ON_OFF=ON
    else
        QT_ON_OFF=OFF
    fi

    QT_LIB=`echo $HOME/Qt*/*/clang_64/lib/cmake`
    QT_QMAKE=`echo $HOME/Qt*/*/clang_64/bin/qmake`

    # Get PATH for Python libraries
    py3_exec=`which python3`
    py3_config=`python3 -c "from distutils.sysconfig import get_config_var as s; print(s('LIBDIR'))"`
    py3_version=`python3 -c "from sys import version_info as s; print('{}.{}'.format(s.major, s.minor))"`
    py3_include=`python3 -c "import distutils.sysconfig as s; print(s.get_python_inc())"`
    py3_packages=`python3 -c "import distutils.sysconfig as s; print(s.get_python_lib())"`
    py3_numpy=`python3 -c "import numpy; print(numpy.get_include())"`

    cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-${OPENCV_VERSION}/modules \
        -D ENABLE_PRECOMPILED_HEADERS=OFF \
        -D WITH_CUDA=OFF \
        -D WITH_QT=${QT_ON_OFF} \
        -D CMAKE_PREFIX_PATH=${QT_LIB} \
        -D QT_QMAKE_EXECUTABLE=${QT_QMAKE} \
        -D QT5Core_DIR=${QT_LIB}/Qt5Core \
        -D QT5Gui_DIR=${QT_LIB}/Qt5Gui \
        -D QT5Test_DIR=${QT_LIB}/Qt5Test \
        -D QT5Widgets_DIR=${QT_LIB}/Qt5Widgets \
        -D Qt5Concurrent_DIR=${QT_LIB}/Qt5Concurrent \
        -D OPENCV_ENABLE_NONFREE=ON \
        -D WITH_GTK=OFF \
        -D WITH_OPENGL=ON \
        -D WITH_OPENVX=ON \
        -D WITH_OPENCL=ON \
        -D WITH_TBB=ON \
        -D WITH_EIGEN=ON \
        -D WITH_GDAL=ON \
        -D WITH_FFMPEG=ON \
        -D BUILD_TIFF=ON \
        -D BUILD_opencv_python2=OFF \
        -D BUILD_opencv_python3=ON \
        -D PYTHON_DEFAULT_EXECUTABLE=${py3_exec} \
        -D PYTHON3_EXECUTABLE=${py3_exec} \
        -D PYTHON3_INCLUDE_DIR=${py3_include} \
        -D PYTHON3_PACKAGES_PATH=${py3_packages} \
        -D PYTHON3_LIBRARY=${py3_config} \
        -D PYTHON3_NUMPY_INCLUDE_DIRS=${py3_numpy} \
        -D INSTALL_PYTHON_EXAMPLES=ON \
        -D INSTALL_C_EXAMPLES=ON \
        -D BUILD_EXAMPLES=ON \
        -D CMAKE_CXX_STANDARD=14 ..

    print magenta "\nmake opencv\n"
    wait_for_user
    make -j"$(nproc)"

    print magenta "\nsudo make install opencv\n"
    wait_for_sudo
    sudo make -j"$(nproc)" install

    print magenta "Removing local files: \n"
    print "${DEVSETUP_PREFIX}/DevSetup/OpenCV/opencv.tar.gz\n"
    print "${DEVSETUP_PREFIX}/DevSetup/OpenCV/opencv_contrib.tar.gz\n\n"
    cd "${DEVSETUP_PREFIX}/DevSetup/OpenCV"
    rm opencv.tar.gz
    rm opencv_contrib.tar.gz

    print yellow frame "# Symlink OpenCV to a new virtual environment\n"
    print yellow "Copy and past the following commands:\n\n"
    print blue "workon <virtual_environment>\n"
    print blue "opencv_lib=\"${DEVSETUP_PREFIX}/DevSetup/OpenCV/opencv/build/lib/python3/*.so\"\n"
    print blue "site_packages=\`python3 -c \"import distutils.sysconfig as s; print(s.get_python_lib())\"\`\n"
    print blue "ln -s \$\{opencv_lib\} \$\{site_packages\}\n\n"

    print green frame "OpenCV installation successful\n"
}

devsetup_install_all() {
    trap "exit 1" SIGINT # Process Interruption Ctrl-C

    print magenta "\nThis script will install:\n"
    print "\thomebrew\n"
    print "\tgit\n"
    print "\tbash\n"
    print "\tbash-tab-completion\n"
    print "\tpyenv\n"
    print "\t~/.inputrc\n"
    print "\t~/.bash-profile\n"

    wait_for_user
    wait_for_sudo
    devsetup_install_homebrew
    devsetup_install_git
    devsetup_install_bash
    devsetup_install_bash_tab_completion
    devsetup_install_pyenv
    devsetup_install_python_libraries
    devsetup_install_jupyterlab
    devsetup_install_ffmpeg
    devsetup_install_opencv
    devsetup_bash_profile_config
    devsetup_inputrc_config
    devsetup_vscode_config
}

devsetup_update_devsetup() {
    print magenta "\nCurrent directory: "
    print "`pwd`\n"
    print magenta "This update installs 'devsetup' to: "
    print "${DEVSETUP_PREFIX}\n"

    wait_for_user

    curl -fsSL "${DEVSETUP_URL}" -o "${DEVSETUP_PREFIX}/DevSetup/bin/devsetup"
    chmod +x "${DEVSETUP_PREFIX}/DevSetup/bin/devsetup"

    print green "\nUpdate successful\n"
}

devsetup_bash_profile_config() {
    if [[ -f ~/.bash_profile ]]; then
        print red "\nThis script will create/overwrite .bash_profile file!\n"
        print magenta "\nA backup will be available: "
        print "~/.bash_profile.bkp\n"

        wait_for_user

        cp ~/.bash_profile ~/.bash_profile.bkp
    fi

    echo "${BASH_PROFILE}" > ${HOME}/.bash_profile
    print green frame "~/.bash_profile configured successful\n"
}

devsetup_inputrc_config() {
    echo "${INPUTRC}" > ${HOME}/.inputrc
    print green frame "~/.inputrc configured successful\n"
}

devsetup_vscode_config() {
    if ! command -v code 1>/dev/null 2>&1; then
        print red "Visual Studio Code is not installed! Install it: "
        print "https://code.visualstudio.com\n"
        exit 1
    fi

    print magenta "Installing Visual Studio Code extensions\n"
    # Code extensions list
    # code --list-extensions | xargs -L 1 echo code --install-extension
    code --install-extension aaron-bond.better-comments
    code --install-extension adamvoss.vscode-languagetool
    code --install-extension adamvoss.vscode-languagetool-en
    code --install-extension adamvoss.vscode-languagetool-fr
    code --install-extension alefragnani.project-manager
    code --install-extension apedroed.Happy-Flasker
    code --install-extension bierner.markdown-preview-github-styles
    code --install-extension christian-kohler.npm-intellisense
    code --install-extension christian-kohler.path-intellisense
    code --install-extension codezombiech.gitignore
    code --install-extension CoenraadS.bracket-pair-colorizer
    code --install-extension cstrap.flask-snippets
    code --install-extension DavidAnson.vscode-markdownlint
    code --install-extension dbaeumer.jshint
    code --install-extension dbaeumer.vscode-eslint
    code --install-extension donjayamanne.git-extension-pack
    code --install-extension donjayamanne.githistory
    code --install-extension donjayamanne.jquerysnippets
    code --install-extension DotJoshJohnson.xml
    code --install-extension eamodio.gitlens
    code --install-extension ecmel.vscode-html-css
    code --install-extension eg2.vscode-npm-script
    code --install-extension eriklynd.json-tools
    code --install-extension esbenp.prettier-vscode
    code --install-extension formulahendry.auto-close-tag
    code --install-extension formulahendry.code-runner
    code --install-extension HookyQR.beautify
    code --install-extension humao.rest-client
    code --install-extension ionutvmi.path-autocomplete
    code --install-extension James-Yu.latex-workshop
    code --install-extension jithurjacob.nbpreviewer
    code --install-extension joelday.docthis
    code --install-extension kisstkondoros.vscode-codemetrics
    code --install-extension kumar-harsh.graphql-for-vscode
    code --install-extension mikestead.dotenv
    code --install-extension ms-python.python
    code --install-extension ms-vscode.cpptools
    code --install-extension ms-vscode.Go
    code --install-extension ms-vsliveshare.vsliveshare
    code --install-extension ms-vsliveshare.vsliveshare-audio
    code --install-extension msjsdiag.debugger-for-chrome
    code --install-extension msjsdiag.vscode-react-native
    code --install-extension njpwerner.autodocstring
    code --install-extension nodesource.vscode-for-node-js-development-pack
    code --install-extension PeterJausovec.vscode-docker
    code --install-extension quicktype.quicktype
    code --install-extension redhat.java
    code --install-extension redhat.vscode-yaml
    code --install-extension ritwickdey.LiveServer
    code --install-extension shd101wyy.markdown-preview-enhanced
    code --install-extension SirTori.indenticator
    code --install-extension timothymclane.react-redux-es6-snippets
    code --install-extension twxs.cmake
    code --install-extension vector-of-bool.cmake-tools
    code --install-extension vscode-icons-team.vscode-icons
    code --install-extension waderyan.gitblame
    code --install-extension wayou.vscode-todo-highlight
    code --install-extension wholroyd.jinja
    code --install-extension wix.vscode-import-cost
    code --install-extension xabikos.JavaScriptSnippets
    code --install-extension yzane.markdown-pdf
    code --install-extension yzhang.markdown-all-in-one
    code --install-extension Zignd.html-css-class-completion
    code --install-extension ziyasal.vscode-open-in-github

    if command -v git 1>/dev/null 2>&1; then
        print magenta "Configuring vscode as default git editor\n"
        git config --global core.editor 'code --wait'

        print magenta "Configuring vscode as default git diff tool\n"
        git config --global diff.tool vscode
        git config --global difftool.vscode.cmd 'code --wait --diff $LOCAL $REMOTE'
    else
        print red "\nGit is not installed!\n"
        print magenta "Install it with: "
        print "devsetup --install git\n"
        print yellow "\nRun this installation again to setup git and vscode!\n\n"
    fi

    print green frame "Visual Studio Code configured successful\n"
}

# Parse devsetup --install options
devsetup_install() {
    sudo -K # Force sudo <command> ask for a root password

    case ${@} in
        "homebrew")
            devsetup_install_homebrew
            ;;
        "git")
            devsetup_install_git
            ;;
        "bash")
            devsetup_install_bash
            ;;
        "bash-tab-completion")
            devsetup_install_bash_tab_completion
            ;;
        "pyenv")
            devsetup_install_pyenv
            ;;
        "pylibs")
            devsetup_install_python_libraries
            ;;
        "jupyterlab")
            devsetup_install_jupyterlab
            ;;
        "ffmpeg")
            devsetup_install_ffmpeg
            ;;
        "opencv")
            devsetup_install_opencv
            ;;
        "all")
            devsetup_install_all
            ;;
        ""|*)
            usage_install_fatal ${@}
            exit 1
            ;;
    esac
}

# Parse devsetup --update options
devsetup_update() {
    sudo -K # Force sudo <command> ask for a root password

    case ${@} in
        "devsetup")
            devsetup_update_devsetup
            ;;
        "git")
            devsetup_git_config
            ;;
        "bash-profile")
            devsetup_bash_profile_config
            ;;
        "inputrc")
            devsetup_inputrc_config
            ;;
        "vscode")
            devsetup_vscode_config
            ;;
        ""|*)
            usage_update_fatal ${@}
            exit 1
            ;;
    esac
}

# Parse devsetup options
while [ "${#}" -gt 0 ]; do
    case ${1} in
        --*'='*)
            shift
            set -- "${1%%=*}" "${1#*=}" "$@"
            continue
            ;;
        -h|--help)
            print_version
            usage
            exit 0
            ;;
        -v|--version)
            print_version
            exit 0
            ;;
        -i|--install)
            shift
            devsetup_install ${1}
            exit 0
            ;;
        -u|--update)
            shift
            devsetup_update ${1}
            exit 0
            ;;
        --|-*|*)
            usage_fatal ${1}
            exit 1
            ;;
    esac
    shift
done
