#!/bin/bash
###########################################################
# Development Environment Setup
#
# Copyright (c) Marcos Gomes-Borges
###########################################################
VERSION="0.0.1"
DEVSETUP_URL="https://raw.githubusercontent.com/marcosgomesborges/dev-setup/master/linux/devsetup"
DEVSETUP_PREFIX=$(dirname $0)

# devsetup usage
###########################################################
usage() {
cat <<EOF
    Usage: devsetup [OPTIONS]

    Option          Long option         Meaning
    -h              --help              Show this help text and exit
    -v              --version           Show the version number of devsetup script
    -i              --install           Install a package
    -u              --update            Update a package
EOF
}

# devsetup install usage
###########################################################
usage_install() {
cat <<EOF
    Usage: devsetup install [SCRIPT]

    Script          Description
    homebrew        Install homebrew package manager for macOS
EOF
}

# devsetup update usage
###########################################################
usage_update() {
cat <<EOF
    Usage: devsetup update [SCRIPT]

    Script          Description
    devsetup        Update devsetup
EOF
}

# Print formated message
# print COLOR FRAME MSG
###########################################################
print() {
    COLOR=${1}
    FRAME=${2}
    MSG=${3}

    case "${COLOR}" in
        *"red"*)
            COLOR="\033[91m";;
        *"green"*)
            COLOR="\033[92m";;
        *"yellow"*)
            COLOR="\033[93m";;
        *"blue"*)
            COLOR="\033[94m";;
        *"magenta"*)
            COLOR="\033[95m";;
        *)
            COLOR="\033[39m";;
    esac

    case "${FRAME}" in
        true)
            echo -e "${COLOR}`printf "=%0.s" {0..79}`"
            echo -e "${COLOR}${MSG}"
            echo -e "${COLOR}`printf "=%0.s" {0..79}`"
            ;;
        false)
            echo -e "${COLOR}${MSG}"
            ;;
    esac

    echo -e "\033[39m" # default color
}

# Print the version number of devsetup script
###########################################################
print_version() {
  echo -e "devsetup ${VERSION}"
}

# sudo password
###########################################################
sudo_password() {
    echo -e "[sudo] Enter password for ${USER}."
    sudo -v
}

# Usage error
###########################################################
usage_fatal() { print red false "${*}"; usage >&2; }
usage_install_fatal() { print red false "${*}"; usage_install >&2; }
usage_update_fatal() { print red false "${*}"; usage_update >&2; }

# devsetup install
###########################################################
devsetup_install() {
    case ${@} in
        ""|*)
            usage_install_fatal "invalid installation command"
            exit 1
            ;;
    esac
}

# devsetup update devsetup
###########################################################
devsetup_update_devsetup() {
    print yellow false "This update installs to ${DEVSETUP_PREFIX}/devsetup"
    print default false "Press RETURN to continue or any other key to abort"

    read -s -n 1 key
    if [[ $key != "" ]]; then
        print red false "\nUpdate aborted!"
        exit 1
    fi

    sudo_password
    sudo curl -fsSL "${DEVSETUP_URL}" -o "${DEVSETUP_PREFIX}/devsetup" && \
    sudo chmod +x "${DEVSETUP_PREFIX}/devsetup"

    print green false "\nUpdate successful"
}

# devsetup update
###########################################################
devsetup_update() {
    case ${@} in
        "devsetup")
            devsetup_update_devsetup
            exit 0
            ;;
        ""|*)
            usage_update_fatal "invalid update command"
            exit 1
            ;;
    esac
}

# Parse options
###########################################################
while [ "${#}" -gt 0 ]; do
    case ${1} in
        --*'='*)
            shift
            set -- "${1%%=*}" "${1#*=}" "$@"
            continue
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -v|--version)
            print_version
            exit 0
            ;;
        -i|--install)
            shift
            devsetup_install ${1}
            exit 0
            ;;
        -u|--update)
            shift
            devsetup_update ${1}
            exit 0
            ;;
        --|-*|*)
            usage_fatal "unknown option: ${1}"
            exit 1
            ;;
    esac
    shift
done
